<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="kilvidiacademy" ignored="0" name="APIParallelTests" tests="10" failures="4" timestamp="19 Mar 2019 22:39:12 GMT" time="2.849" errors="0">
  <testcase name="AuthenticationBasics" time="1.239" classname="RestApi.APITest.Authentication">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at RestApi.APITest.Authentication.AuthenticationBasics(Authentication.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:80)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
... 17 more
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- AuthenticationBasics -->
  <testcase name="DisplayAllNodesInWeatherAPI" time="1.239" classname="RestApi.APITest.GetTest">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at RestApi.APITest.GetTest.DisplayAllNodesInWeatherAPI(GetTest.java:173)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:80)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
... 17 more
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- DisplayAllNodesInWeatherAPI -->
  <testcase name="RegistrationSuccessful" time="1.361" classname="RestApi.APITest.RegistrationSuccessResponse"/>
  <testcase name="SimplePostTest" time="1.621" classname="RestApi.APITest.PostTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RestApi.APITest.PostTest.SimplePostTest(PostTest.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- SimplePostTest -->
  <testcase name="GetWeatherDetails" time="0.421" classname="RestApi.APITest.GetTest"/>
  <testcase name="GetWeatherDetailsInvalidCity" time="0.224" classname="RestApi.APITest.GetTest">
    <failure type="java.lang.AssertionError" message="Correct status code returned expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: Correct status code returned expected [200] but found [400]
at RestApi.APITest.GetTest.GetWeatherDetailsInvalidCity(GetTest.java:74)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- GetWeatherDetailsInvalidCity -->
  <testcase name="GetWeatherHeaders" time="0.224" classname="RestApi.APITest.GetTest"/>
  <testcase name="GetWeatherStatusLine" time="0.242" classname="RestApi.APITest.GetTest"/>
  <testcase name="IteratingOverHeaders" time="0.218" classname="RestApi.APITest.GetTest"/>
  <testcase name="WeatherMessageBody" time="0.229" classname="RestApi.APITest.GetTest"/>
</testsuite> <!-- APIParallelTests -->
